### ISSUE TITLE
ClassCastException when getting deployments

### ISSUE THREAD

**Issue by helder-goncalves-cko** [matt-richardson/teamcity-octopus-build-trigger-plugin#8]
Hi,

Not sure if you are still maintaining this awesome plugin, but I'm having an issue with my build trigger:

```
jetbrains.buildServer.buildTriggers.BuildTriggerException: Octopus Deployment Complete Trigger failed with error: Unexpected exception in DeploymentsProviderImpl, while attempting to get deployments from http://myoctopusserver:8088: java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to java.util.Map 
at com.mjrichardson.teamCity.buildTriggers.DeploymentComplete.DeploymentCompleteAsyncBuildTrigger.makeTriggerException(DeploymentCompleteAsyncBuildTrigger.java:61)
at com.mjrichardson.teamCity.buildTriggers.CustomAsyncPolledBuildTrigger.mapCheckResultToJobResult(CustomAsyncPolledBuildTrigger.java:81)
at com.mjrichardson.teamCity.buildTriggers.CustomAsyncPolledBuildTrigger.triggerBuild(CustomAsyncPolledBuildTrigger.java:47)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$5.run(BuildTriggersChecker.java:3) 
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:74) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:63) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1200(BuildTriggersChecker.java:37) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:54)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$2.run(BuildTriggersChecker.java:2) 
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:74) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:113) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java:3) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:43)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:52) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: com.mjrichardson.teamCity.buildTriggers.DeploymentComplete.DeploymentsProviderException: Unexpected exception in DeploymentsProviderImpl, while attempting to get deployments from http://myoctopusserver:8080: java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to java.util.Map 
at com.mjrichardson.teamCity.buildTriggers.DeploymentComplete.DeploymentsProviderImpl.getDeployments(DeploymentsProviderImpl.java:41)
at com.mjrichardson.teamCity.buildTriggers.DeploymentComplete.DeploymentCompleteCheckJob.getCheckResult(DeploymentCompleteCheckJob.java:78)
at com.mjrichardson.teamCity.buildTriggers.DeploymentComplete.DeploymentCompleteCheckJob.perform(DeploymentCompleteCheckJob.java:162)
at com.mjrichardson.teamCity.buildTriggers.CustomAsyncPolledBuildTrigger.lambda$submitCheckJob$0(CustomAsyncPolledBuildTrigger.java:153)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
... 1 more 
Caused by: java.lang.ClassCastException: org.json.simple.JSONArray cannot be cast to java.util.Map 
at com.mjrichardson.teamCity.buildTriggers.ApiProgressionResponse.AddDeployments(ApiProgressionResponse.java:66)
at com.mjrichardson.teamCity.buildTriggers.ApiProgressionResponse.Parse(ApiProgressionResponse.java:44) 
at com.mjrichardson.teamCity.buildTriggers.ApiProgressionResponse.<init>(ApiProgressionResponse.java:23) 
at com.mjrichardson.teamCity.buildTriggers.DeploymentComplete.DeploymentsProviderImpl.getDeployments(DeploymentsProviderImpl.java:47)
at com.mjrichardson.teamCity.buildTriggers.DeploymentComplete.DeploymentsProviderImpl.getDeployments(DeploymentsProviderImpl.java:36)
... 6 more
```

Any ideas?

Thanks!

**Comment by matt-richardson** [comment]
Hi @helder-goncalves-cko 

I'm not currently using this, but its not officially dead yet :)

Can you let me know what version of Octopus you are using? (And what version of TC, just in case)

Also, can you [turn on](https://github.com/matt-richardson/teamcity-octopus-build-trigger-plugin#logging) `DEBUG` logs, and share the results? You will need to scrub them to remove any sensitive info. All I'll really need is the response from the `progression` api.

**Comment by nvborisenko** [comment]
Octopus version is 3.11.13.

**Comment by matt-richardson** [comment]
I've found that there was a breaking change in one of the Octopus api's, which I wasn't aware about.
I've just pushed a new version - [2.5.1](https://github.com/matt-richardson/teamcity-octopus-build-trigger-plugin/releases/tag/2.5.1%2Bbuild.146) that should fix it.

Sorry for the delay in getting to this.

Let me know how it goes.
